import { lazy, Suspense, useState } from 'react';
import { ChevronDown, ChevronRight, MessageCircleQuestion, Mail, BookOpen } from 'lucide-react';
import { OverlayPage } from '../components/layout/OverlayPage';
import { useAuth } from '../contexts/AuthContext';

/**
 * Pass 32 X10 — /help page rewrite + Ask VETT mount.
 *
 * Content rewritten to match Pass 31 Z1 / Z2 honest claims:
 *   - No "verified humans" / "ID-verified via government databases"
 *   - No "100% accuracy"
 *   - VETT is methodology-first, synthetic-respondent research powered
 *     by Claude — explicit about what the tool is and isn't.
 *
 * Ask VETT chatbot mounts inline at the bottom for authenticated users
 * (uses the existing dashboard-scope copilot, 30 messages / month).
 * Anonymous visitors see a sign-in CTA where the chat would render.
 */

const ChatWidget = lazy(() =>
  import('../components/chat/ChatWidget').then(m => ({ default: m.ChatWidget })),
);

interface FAQ {
  category: string;
  question: string;
  answer: string;
}

const FAQS: FAQ[] = [
  {
    category: 'How VETT works',
    question: 'How does VETT generate answers?',
    answer:
      'Every mission runs through a multi-stage pipeline powered by Anthropic Claude models. We generate a population of synthetic respondents calibrated to your audience, simulate each one answering your questions in their own voice, then synthesize the responses into directional insights. Numeric outputs are model-derived — we treat them as decision-support signals, not as census-grade truth.',
  },
  {
    category: 'How VETT works',
    question: 'Are these answers from real people?',
    answer:
      'No. VETT delivers synthetic respondents — AI personas that simulate how a defined audience would likely respond. We do not panel real consumers, do not collect PII, and do not claim panel-level statistical validity. The advantage is speed and cost; the trade-off is that you treat the output as a fast directional read, not a substitute for a representative sample on high-stakes decisions.',
  },
  {
    category: 'How VETT works',
    question: 'Which research methodologies do you support?',
    answer:
      'Brand Lift (incrementality, exposed vs control), Creative Attention (frame-by-frame video / static analysis with attention prediction + emotion taxonomy), Pricing (Van Westendorp + Gabor-Granger), Feature Roadmap (MaxDiff + Kano), Customer Satisfaction (NPS + CSAT + CES), Concept Test, Sequential Monadic Comparison, Ad Effectiveness, Brand Health Tracker, Naming & Messaging (Monadic + Paired + TURF), and Churn (Driver Tree + Win-Back). Each runs an industry-standard research framework — the prompt, simulation, and synthesis layers are tuned per type. The frameworks themselves are peer-reviewed in the academic literature; VETT outputs are synthetic-respondent simulations of those frameworks.',
  },
  {
    category: 'Pricing',
    question: 'How is a mission priced?',
    answer:
      'Base price scales with respondent count: $99 for 50 respondents up to $999 for 1,000 respondents. Targeting depth (geo, behavioral, professional) adds a surcharge — broader targeting is cheaper, multi-criteria narrow targeting costs more. Extra questions beyond the included 10 are $1.50 each. Promo codes apply at checkout. The full breakdown shows on the launch screen before any payment.',
  },
  {
    category: 'Pricing',
    question: 'Do you charge per-message for the AI copilot?',
    answer:
      'Each mission ships with 30 chat messages on the results page (per-mission quota). The dashboard copilot has 30 messages per calendar month. The setup advisor has 20 messages per draft mission. If you need more, you can purchase 50 additional messages for $5 from the chat widget itself.',
  },
  {
    category: 'Pricing',
    question: 'What if a mission fails to deliver?',
    answer:
      'If a mission completes with fewer respondents than contracted, we automatically partial-refund the difference to the original payment method. Full failures (analysis errors, payment issues) trigger a full refund. The refund is processed within 24 hours via Stripe and you receive an email confirmation.',
  },
  {
    category: 'Targeting',
    question: 'Can I target by country, age, or job title?',
    answer:
      'Yes — geography (160+ countries), age ranges, gender, education, marital + parental status, employment, industry, seniority, company size, and behavioral attributes. The targeting picker lets you stack any number of criteria. Narrow combinations (e.g. CMOs at SaaS companies in Germany) cost more because the persona generator has to honor every constraint when synthesizing the population.',
  },
  {
    category: 'Targeting',
    question: 'How accurate is the targeting?',
    answer:
      'Personas are generated by Claude conditioned on your target spec — the model writes population members that fit the criteria. Targeting fidelity depends on how clearly the criteria are specified and how much real-world signal the model has on that segment. We surface a targeting summary on every mission so you can sanity-check before launch.',
  },
  {
    category: 'Outputs',
    question: 'What do I get when a mission completes?',
    answer:
      'A results page with executive summary, per-question aggregations (single/multi/rating distributions, sentiment for free-text), persona profiles, screening funnel, and methodology-specific cards (e.g. price elasticity curves for pricing missions, attention decay curves for creative missions). All exportable as JSON, CSV, PDF, PowerPoint, or Excel.',
  },
  {
    category: 'Outputs',
    question: 'Can I share results with my team?',
    answer:
      'You can export the results to PDF / PowerPoint / Excel and share those files directly. We do not currently offer multi-user workspace sharing — each account owns its missions. If you need team access, contact us and we will work out a workspace setup for your team.',
  },
  {
    category: 'Data & privacy',
    question: 'What data do you collect?',
    answer:
      'Account data (email, name, company), mission inputs (briefs, questions, targeting, uploaded creative assets), and usage telemetry. We do not collect PII from any "respondents" because there are no real respondents — every answer is synthetic. Mission data is private to your account by default.',
  },
  {
    category: 'Data & privacy',
    question: 'Can I delete my data?',
    answer:
      'Yes. From your profile page you can delete individual missions or your entire account. Account deletion removes all associated missions, responses, chat sessions, and notifications within 30 days. Stripe payment records are retained per finance regulations.',
  },
];

const CATEGORIES = Array.from(new Set(FAQS.map(f => f.category)));

const GUIDES = [
  {
    title: 'Writing better questions',
    description: 'How to phrase questions to surface honest, decision-grade signal — and which leading-question patterns to avoid.',
  },
  {
    title: 'Choosing a methodology',
    description: 'Brand Lift vs Concept Test vs Pricing — when each one fits, and how to combine them on the same product.',
  },
  {
    title: 'Reading creative attention scores',
    description: 'Active vs passive attention, distinctive brand asset score, and how to interpret the per-frame emotion arc.',
  },
  {
    title: 'Targeting depth, explained',
    description: 'When to use Gen Pop, when to narrow to a niche, and how the targeting surcharge maps to persona accuracy.',
  },
];

export const HelpPage = () => {
  const { user } = useAuth();
  const [openId, setOpenId] = useState<string | null>(null);
  const [askOpen, setAskOpen] = useState(false);

  return (
    <OverlayPage>
      <div className="max-w-4xl mx-auto">
        <h1 className="text-5xl md:text-7xl font-black tracking-tighter text-white mb-6">
          Help Center
        </h1>
        <p className="text-white/60 text-xl mb-16 max-w-2xl">
          What VETT is, how missions work, and what the outputs actually mean.
          Methodology-first, synthetic respondents — read the FAQ before launching.
        </p>

        {/* FAQ */}
        <div className="mb-16">
          <h2 className="text-3xl font-black text-white mb-8 uppercase tracking-tight">
            Frequently Asked Questions
          </h2>

          {CATEGORIES.map((cat) => (
            <div key={cat} className="mb-8">
              <h3 className="text-xs font-black text-primary uppercase tracking-widest mb-4">
                {cat}
              </h3>
              <div className="space-y-3">
                {FAQS.filter(f => f.category === cat).map((faq, idx) => {
                  const id = `${cat}-${idx}`;
                  const open = openId === id;
                  return (
                    <button
                      key={id}
                      type="button"
                      onClick={() => setOpenId(open ? null : id)}
                      className="w-full text-left glass-panel rounded-2xl border border-white/5 hover:border-white/15 transition-all overflow-hidden"
                      aria-expanded={open}
                    >
                      <div className="flex items-center justify-between gap-4 p-6">
                        <h4 className="text-lg font-black text-white pr-4">
                          {faq.question}
                        </h4>
                        <ChevronDown
                          className={`w-5 h-5 text-white/40 transition-transform shrink-0 ${open ? 'rotate-180' : ''}`}
                          aria-hidden
                        />
                      </div>
                      {open && (
                        <div className="px-6 pb-6 -mt-1">
                          <p className="text-white/70 leading-relaxed">{faq.answer}</p>
                        </div>
                      )}
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Guides */}
        <div className="mb-16">
          <h2 className="text-3xl font-black text-white mb-8 uppercase tracking-tight flex items-center gap-3">
            <BookOpen className="w-7 h-7 text-primary" />
            Guides &amp; Tutorials
          </h2>
          <div className="grid sm:grid-cols-2 gap-4">
            {GUIDES.map((guide) => (
              <div
                key={guide.title}
                className="glass-panel p-6 rounded-2xl border border-white/5 hover:border-primary/40 transition-all group"
              >
                <h3 className="text-white font-bold group-hover:text-primary transition-colors mb-2">
                  {guide.title}
                </h3>
                <p className="text-white/50 text-sm leading-relaxed">
                  {guide.description}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Ask VETT — inline copilot for authed users, sign-in CTA otherwise */}
        <div className="mb-16">
          <h2 className="text-3xl font-black text-white mb-4 uppercase tracking-tight flex items-center gap-3">
            <MessageCircleQuestion className="w-7 h-7 text-primary" />
            Ask VETT
          </h2>
          <p className="text-white/60 mb-6">
            Couldn&apos;t find what you&apos;re looking for? Ask the dashboard copilot
            anything about your missions, methodologies, or how to interpret a result.
          </p>
          {user ? (
            <>
              <button
                type="button"
                onClick={() => setAskOpen(true)}
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-primary text-black font-black text-sm uppercase tracking-widest hover:opacity-90 transition-opacity"
              >
                <MessageCircleQuestion className="w-4 h-4" />
                Open Ask VETT
              </button>
              <Suspense fallback={null}>
                <ChatWidget
                  scope="dashboard"
                  anchor="inline"
                  isOpen={askOpen}
                  onClose={() => setAskOpen(false)}
                  title="Ask VETT"
                />
              </Suspense>
            </>
          ) : (
            <a
              href="/signin"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-white/5 border border-white/15 text-white font-black text-sm uppercase tracking-widest hover:bg-white/10 transition-colors"
            >
              <MessageCircleQuestion className="w-4 h-4" />
              Sign in to use Ask VETT
            </a>
          )}
        </div>

        {/* Contact */}
        <div className="text-center glass-panel p-12 rounded-3xl border border-white/5">
          <h3 className="text-2xl font-black text-white mb-4">Still stuck?</h3>
          <p className="text-white/60 mb-6 max-w-md mx-auto">
            Email support directly. We aim for a response within one business day.
          </p>
          <a
            href="mailto:support@vettit.ai"
            className="inline-flex items-center gap-2 px-8 py-4 rounded-full font-black text-sm uppercase tracking-widest bg-[#DFFF00] hover:bg-[#E5FF40] text-black shadow-lg shadow-[#DFFF00]/30 hover:shadow-[#DFFF00]/40 transition-all duration-300 hover:scale-105"
          >
            <Mail className="w-4 h-4" />
            Contact Support
          </a>
        </div>

        {/* Footer link to category index */}
        <div className="mt-12 flex items-center justify-center gap-2 text-white/40 text-sm">
          {CATEGORIES.map((cat) => (
            <a
              key={cat}
              href={`#${cat.replace(/\s+/g, '-').toLowerCase()}`}
              className="hover:text-white/70 transition-colors flex items-center gap-1"
            >
              {cat} <ChevronRight className="w-3 h-3" />
            </a>
          ))}
        </div>
      </div>
    </OverlayPage>
  );
};

export default HelpPage;
