/**
 * Generate public/sitemap.xml from the same manifest the prerenderer uses.
 *
 * The hand-maintained sitemap listed 16 URLs and carried no <lastmod>. Six of
 * the eleven /vs comparison pages were missing entirely, and every URL it DID
 * list was canonicalised to the homepage by the shell - so it was submitting
 * pages and then telling the crawler to ignore them.
 *
 * Generating it from the manifest means adding a public route adds it to the
 * sitemap, with a canonical that points at itself.
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITEMAP_ROUTES, canonicalFor } from './seo-routes.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const lastmod = new Date().toISOString().slice(0, 10);

const urls = SITEMAP_ROUTES.map((r) => `  <url>
    <loc>${canonicalFor(r)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  VETT - sitemap.xml. GENERATED by scripts/sitemap.mjs from scripts/seo-routes.mjs.
  Do not hand-edit: add the route to the manifest instead, so its canonical tag
  and its sitemap entry can never disagree.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

writeFileSync(join(ROOT, 'public', 'sitemap.xml'), xml, 'utf8');
console.log(`sitemap: wrote ${SITEMAP_ROUTES.length} URLs with lastmod ${lastmod}`);
